#!/bin/bash

#skript väljastab 5 rida tärne vastavalt rea numbrile

echo -n "Sisestage ridade arv: "
read rida

for ((wa=1; wa<= $rida ; wa++ ))
do
echo -n "$wa."
for (( wo=1; wo<=$wa; wo++))
do
echo -n "*"
done
echo "" 
done
