#!/bin/bash

#väljasta lause kasutades muutujaid

#panen paika muutujad
aasta="2016"

president="Kersti Kaljulaid"

lause_keskosa=". aastal valiti Eesti presidentiks "

#paneme lause kokku
lause=" $aasta$lause_keskosa $president"

echo $lause
